version: "3"
services:
  web:
    build: .
    ports:
      - "4500:4500"
    volumes:
      - .:/home/node/src
      - /home/node/src/node_modules
    links:
      - db
    environment:
      mongodbURL: mongodb://db:27017
  db:
    image: mongo:3
